### ISSUE TITLE
Error when compile

### ISSUE THREAD

**Issue by vienhx** [awslabs/aws-elasticache-cluster-client-libmemcached#23]
I get some errors while compiling:

`#17 43.90 ../libmemcached/server.cc: In function 'const char* memcached_server_ipaddress(memcached_instance_st)':
#17 43.90 ../libmemcached/server.cc:268:11: error: could not convert 'self' from 'const memcached_instance_st' to 'bool'
#17 43.90    if (self)
#17 43.90            ^
#17 43.90 ../libmemcached/server.cc:270:16: error: base operand of '->' has non-pointer type 'const memcached_instance_st'
#17 43.90      return self->_ipaddress;`

It seems caused by PR https://github.com/awslabs/aws-elasticache-cluster-client-libmemcached/pull/18

**Comment by dragos-dumi** [comment]
I also get an error when compiling
../libtest/cmdline.cc:65:15: error: 'environ' was declared 'extern' and later 'static' [-fpermissive]
   65 | static char **environ= NULL;
