### PR TITLE
Fix build failure and automake support

### PR DESCRIPTION
**Pull request by jdolinski**
#9 #8 #7 

@kmaleyev I created a new pull request to more clearly define the changes and incorporate your feedback. I have tested the build on Ubuntu 14 and Amazon Linux 2017.03

I organized this PR more cleanly and discarded some changes after your clarification and feedback. I tried squashing but it got really ugly and wanted to be clear on the changes. 

Let me know your thoughts, thanks in advance.

### CODE REVIEW

File: tests/libmemcached-1.0/all_tests.cc [hunk 1]
```diff
@@ -71,7 +71,7 @@
 
 #include <algorithm>
```
Comment (jdolinski) [inline tests/libmemcached-1.0/all_tests.cc]: During linking of the test cases and prod files was running into the error below. I had renamed a couple methods that contained the same signature causing multiple definition errors. 

`  CXXLD    tests/libmemcached-1.0/testapp
tests/libmemcached-1.0/tests_libmemcached_1_0_testapp-dynamic_mode_test.o: In function `get_world':
/usr/include/c++/4.8/sstream:129: multiple definition of `get_world'
tests/libmemcached-1.0/tests_libmemcached_1_0_testapp-all_tests.o:/home/ubuntu/new/aws-elasticache-cluster-client-libmemcached/BUILD/../tests/libmemcached-1.0/all_tests.cc:75: first defined here
tests/libmemcached-1.0/tests_libmemcached_1_0_testapp-dynamic_mode_test.o:(.data.rel+0x0): multiple definition of `collection'
tests/libmemcached-1.0/tests_libmemcached_1_0_testapp-all_tests.o:(.data.rel+0x0): first defined here
/usr/bin/ld: Warning: size of symbol `collection' changed from 2272 in tests/libmemcached-1.0/tests_libmemcached_1_0_testapp-all_tests.o to 64 in tests/libmemcached-1.0/tests_libmemcached_1_0_testapp-dynamic_mode_test.o
collect2: error: ld returned 1 exit status
`

File: libmemcached-1.0/struct/include.am [hunk 2]
```diff
@@ -9,6 +9,5 @@ nobase_include_HEADERS+= libmemcached-1.0/struct/memcached.h
 nobase_include_HEADERS+= libmemcached-1.0/struct/result.h 
 nobase_include_HEADERS+= libmemcached-1.0/struct/sasl.h 
 nobase_include_HEADERS+= libmemcached-1.0/struct/server.h
-nobase_include_HEADERS+= libmemcached-1.0/struct/configuration_server.h
```
Comment (jdolinski) [inline libmemcached-1.0/struct/include.am]: Dead code

File: libmemcached/include.am [hunk 3]
```diff
@@ -24,8 +24,7 @@ noinst_HEADERS+= libmemcached/continuum.hpp
 noinst_HEADERS+= libmemcached/do.hpp 
 noinst_HEADERS+= libmemcached/encoding_key.h 
 noinst_HEADERS+= libmemcached/error.hpp 
-noinst_HEADERS+= libmemcached/flag.hpp 
-noinst_HEADERS+= libmemcached/host.h
```
Comment (jdolinski) [inline libmemcached/include.am]: Dead code

File: libtest/include.am [hunk 4]
```diff
@@ -192,6 +193,7 @@ $(TMP_DIR):
 	@$(mkdir_p) $(TMP_DIR)
 
 libtest_unittest_LDADD+= libtest/libtest.la
+libtest_unittest_LDADD+= $(libmemcached_libmemcached_la_OBJECTS)
 libtest_unittest_SOURCES= libtest/unittest.cc
```
Comment (jdolinski) [inline libtest/include.am]: Modified the automake include files to fix compiling/linking errors when referencing memcached functions

**Comment by jdolinski** [comment]
Hi Kosty,
Sorry about submitting a second pull request but I had problems squashing. Once I received your feedback, I realized I had made some assumptions that were not true. Look forward to your feedback and thoughts.

**Comment by raphaelquati** [comment]
I'm trying to use your PR, to create a docker image to run in ECR.
I'm using  PHP-7.1.5 image (debian:jessie).

```
apt install automake autoconf libtool git shtool autogen
git clone ......
cd .....
rm -rf .git
autoreconf -vfi
mkdir BUILD
cd BUILD
../configure --prefix=$(pwd)/local --with-pic

```

The configure gives error: 

```
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
configure: error: cannot find install-sh, install.sh, or shtool in ".." "../.." "../../.."
```

Checking the build-aux dir (created by autoreconf):

```
root@0546d5a47108:/tmp/aws-elasticache-cluster-client-libmemcached/build-aux# ls -l
total 424
-rwxr-xr-x 1 root root   7333 Jun 22 19:36 compile
-rwxr-xr-x 1 root root  42856 Jun 22 19:36 config.guess
-rwxr-xr-x 1 root root  35837 Jun 22 19:36 config.sub
-rwxr-xr-x 1 root root  23566 Jun 22 19:36 depcomp
-rwxr-xr-x 1 root root  14431 Jun 22 19:36 install-sh
-rw-r--r-- 1 root root 283672 Jun 22 19:36 ltmain.sh
-rwxr-xr-x 1 root root   6872 Jun 22 19:36 missing
-rwxr-xr-x 1 root root   4287 Jun 22 19:37 test-driver
```

**Comment by allyraza** [comment]
@raphaelquati you can sym shtool into the dir you extract 
`configure: error: cannot find install-sh, install.sh, or shtool in ".." "../.." "../../.."`
