### ISSUE TITLE
Compile failure :: Latest release

### ISSUE THREAD

**Issue by dev-head** [awslabs/aws-elasticache-cluster-client-libmemcached#7]
Our systems are showing errors when building from the latest release: (Full output saved at pastebin: http://pastebin.com/raw/66JS1AnL)

### Error:
```
CDPATH="${ZSH_VERSION+.}:" && cd .. && /bin/bash /tmp/compile/libmemcached/aws-elasticache-cluster-client-libmemcached/build-aux/missing aclocal-1.13 -I m4 -I libtest/m4
/tmp/compile/libmemcached/aws-elasticache-cluster-client-libmemcached/build-aux/missing: line 81: aclocal-1.13: command not found
WARNING: 'aclocal-1.13' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:3776: recipe for target '../aclocal.m4' failed
make: *** [../aclocal.m4] Error 127
```

Configured:
```
Configuration summary for libmemcached version 1.0.18

   * Installation prefix:       /usr/lib/x86_64-linux-gnu
   * System type:               unknown-linux-gnu
   * Host CPU:                  x86_64
   * C Compiler:                cc (Debian 4.9.2-10) 4.9.2
   * C Flags:                   -g -O2  -Wno-unknown-pragmas -Wno-pragmas -Wall -Wextra -Wunsuffixed-float-constants -Wjump-misses-init -Wno-attributes -Waddress -Wvarargs -Warray-bounds -Wbad-function-cast -Wchar-subscripts -Wcomment -Wfloat-equal -Wformat-security -Wformat=2 -Wformat-y2k -Wlogical-op -Wmaybe-uninitialized -Wmissing-field-initializers -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wnormalized=id -Woverride-init -Wpointer-arith -Wpointer-sign -Wredundant-decls -Wshadow -Wsign-compare -Wstrict-overflow=1 -Wswitch-enum -Wtrampolines -Wundef -Wunsafe-loop-optimizations -funsafe-loop-optimizations -Wclobbered -Wunused -Wunused-result -Wunused-variable -Wunused-parameter -Wunused-local-typedefs -Wwrite-strings -fwrapv -pipe -fPIE -pie -Wsizeof-pointer-memaccess -Wpacked
   * C++ Compiler:              c++ (Debian 4.9.2-10) 4.9.2
   * C++ Flags:                 -g -O2 -Wno-unknown-pragmas -Wno-pragmas -Wall -Wextra -Wno-attributes -Wvarargs -Waddress -Warray-bounds -Wchar-subscripts -Wcomment -Wctor-dtor-privacy -Wfloat-equal -Wformat=2 -Wformat-y2k -Wmaybe-uninitialized -Wmissing-field-initializers -Wlogical-op -Wnon-virtual-dtor -Wnormalized=id -Woverloaded-virtual -Wpointer-arith -Wredundant-decls -Wshadow -Wsign-compare -Wstrict-overflow=1 -Wswitch-enum -Wtrampolines -Wundef -Wunsafe-loop-optimizations -funsafe-loop-optimizations -Wc++11-compat -Wclobbered -Wunused -Wunused-result -Wunused-variable -Wunused-parameter -Wunused-local-typedefs -Wwrite-strings -Wformat-security -fwrapv -pipe -fPIE -pie -Wsizeof-pointer-memaccess -Wpacked
   * CPP Flags:                  -fvisibility=hidden
   * LIB Flags:                 
   * Assertions enabled:        no
   * Debug enabled:             no
   * Shared:                    yes
   * Warnings as failure:       no
   * SASL support:              no
   * make -j:                   3
   * VCS checkout:              no
```

**Comment by alekitto** [comment]
Same problem trying to compile on Ubuntu 16.04
You can try this: https://github.com/alekitto/aws-elasticache-cluster-client-libmemcached
Should compile executing `autoreconf -i -f` before `./configure`, but hasn't been tested yet

**Comment by malyeyev-AMZN** [comment]
Please do not use autotools/autoreconf. We have modified Makefile.in directly and have not tested if it builds correctly with autoconf, so you may end up with more problems down the road as a result of this.

Instead, to resolve this issued do

> touch configure.ac aclocal.m4 configure Makefile.am Makefile.in

before running ./configure

**Comment by kwilczynski** [comment]
Hi @malyeyev-AMZN would you be able to update the code so that it works for everyone with autotools, etc? At the moment building this driver is somewhat not easy, and not everyone is using Amazon Linux, etc. I (and many others) would be much obliged :)

**Comment by Seegras** [comment]
Breaks on Ubuntu 18.04 LTS. 

> ../clients/memflush.cc: In function ‘int main(int, char**)’:
> ../clients/memflush.cc:42:22: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
>    if (opt_servers == false)
>                       ^~~~~
> ../clients/memflush.cc:51:24: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
>      if (opt_servers == false)
>                         ^~~~~
> Makefile:5881: recipe for target 'clients/memflush.o' failed
> make[1]: *** [clients/memflush.o] Error 1

This is with the "touch" from above, otherwise it complains about missing some ancient version of autotools.

**Comment by evanNMSG** [comment]
> Breaks on Ubuntu 18.04 LTS.
> 
> > ../clients/memflush.cc: In function ‘int main(int, char**)’:
> > ../clients/memflush.cc:42:22: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
> > if (opt_servers == false)
> > ^~~~~
> > ../clients/memflush.cc:51:24: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
> > if (opt_servers == false)
> > ^~~~~
> > Makefile:5881: recipe for target 'clients/memflush.o' failed
> > make[1]: *** [clients/memflush.o] Error 1
> 
> This is with the "touch" from above, otherwise it complains about missing some ancient version of autotools.

Was there ever a fix for this?
